on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python ./sleep.py`

  build-two:
    runs-on: ubuntu-latest
    steps:
      - run: python -c "exec(\"import sys\ndef signal_handler(sig, frame):\nprint('Ctrl+C!')\nsys.exit(1)\nsignal.signal(signal.SIGINT, signal_handler)\nwait()\")"
